import {product, filter} from './interface'
import {policy} from './interface'
import {AiOutlineShopping,AiOutlineCreditCard} from 'react-icons/ai'
import {BsFillXDiamondFill} from 'react-icons/bs'
import {BiDonateHeart} from 'react-icons/bi'
export const products:Array<product> = [
    {
        title: 'Smart Pants',
        price: '419.000',
        priceold:'123.000',
        image01: 'https://github.com/quangloc2708/Ecommerce-Web-Shop/blob/main/src/assets/Images/products/prd1.1.jpeg?raw=true',
        image02: 'https://github.com/quangloc2708/Ecommerce-Web-Shop/blob/main/src/assets/Images/products/prd1.2.jpeg?raw=true',
        categorySlug: 'Quần tây',
        colors: ['White', 'Red', 'Yellow'],
        slug: 'smart pants',
        size: ['s', 'm', 'l', 'xl'],
        decription: 'Áo sơ mi nam form refined fit SSSTUTTER chất bamboo sơ vin linh hoạt FIT SHIRT',
        color_info: 'trắng be, vàng cát, đen, xanh mint, ghi nhạt',
        size_info: '0/1/2/3 tương ứng với S/M/L/XL ',
        material: 'vải bamboo (thoáng mát và không nhăn)',
        form: 'vải bamboo (thoáng mát và không nhăn)',
        origin: 'Việt Nam',
        gender: 'nam',
    },
    {
        title: 'Great Life Tee',
        price: '645.00',
        priceold:'123.000',
        image01: 'https://github.com/quangloc2708/Ecommerce-Web-Shop/blob/main/src/assets/Images/products/prd10.1.jpeg?raw=true',
        image02: 'https://github.com/quangloc2708/Ecommerce-Web-Shop/blob/main/src/assets/Images/products/prd10.2.jpeg?raw=true',
        categorySlug: 'Áo thun',
        colors: ['White', 'Red', 'Blue'],
        slug: 'great-life-tee',
        size: ['s', 'm'],
        decription: 'Áo sơ mi nam form refined fit SSSTUTTER chất bamboo sơ vin linh hoạt FIT SHIRT',
        color_info: 'trắng be, vàng cát, đen, xanh mint, ghi nhạt',
        size_info: '0/1/2/3 tương ứng với S/M/L/XL ',
        material: 'vải bamboo (thoáng mát và không nhăn)',
        form: 'vải bamboo (thoáng mát và không nhăn)',
        origin: 'Việt Nam',
        gender: 'nam',
    },
    {
        title: 'Man Shirt',
        price: '379.000',
        priceold:'123.000',
        image01: 'https://github.com/quangloc2708/Ecommerce-Web-Shop/blob/main/src/assets/Images/products/prd11.1.jpeg?raw=true',
        image02: 'https://github.com/quangloc2708/Ecommerce-Web-Shop/blob/main/src/assets/Images/products/prd11.2.jpeg?raw=true',
        categorySlug: 'Áo sơ mi',
        colors: ['White', 'Red', 'Yellow', 'Blue'],
        slug: 'man-shirt',
        size: ['m'],
        decription: 'Áo sơ mi nam form refined fit SSSTUTTER chất bamboo sơ vin linh hoạt FIT SHIRT',
        color_info: 'trắng be, vàng cát, đen, xanh mint, ghi nhạt',
        size_info: '0/1/2/3 tương ứng với S/M/L/XL ',
        material: 'vải bamboo (thoáng mát và không nhăn)',
        form: 'vải bamboo (thoáng mát và không nhăn)',
        origin: 'Việt Nam',
        gender: 'nam',
    },
    {
        title: 'Stone Shorts',
        price: '194.000',
        priceold:'123.000',
        image01: 'https://github.com/quangloc2708/Ecommerce-Web-Shop/blob/main/src/assets/Images/products/prd12.1.jpeg?raw=true',
        image02: 'https://github.com/quangloc2708/Ecommerce-Web-Shop/blob/main/src/assets/Images/products/prd12.2.jpeg?raw=true',
        categorySlug: 'Quần tây',
        colors: ['white', 'Orange', 'Blue'],
        slug: 'stone-shorts',
        size: ['xl'],
        decription: 'Áo sơ mi nam form refined fit SSSTUTTER chất bamboo sơ vin linh hoạt FIT SHIRT',
        color_info: 'trắng be, vàng cát, đen, xanh mint, ghi nhạt',
        size_info: '0/1/2/3 tương ứng với S/M/L/XL ',
        material: 'vải bamboo (thoáng mát và không nhăn)',
        form: 'vải bamboo (thoáng mát và không nhăn)',
        origin: 'Việt Nam',
        gender: 'nam',
    },
    {
        title: 'Felix Shirt',
        price: '194.000',
        priceold:'123.000',
        image01: 'https://github.com/quangloc2708/Ecommerce-Web-Shop/blob/main/src/assets/Images/products/prd2.1.jpeg?raw=true',
        image02: 'https://github.com/quangloc2708/Ecommerce-Web-Shop/blob/main/src/assets/Images/products/prd2.2.jpeg?raw=true',
        categorySlug: 'Áo sơ mi',
        colors: ['white', 'pink'],
        slug: 'felix-shirt',
        size: ['xxl'],
        decription: 'Áo sơ mi nam form refined fit SSSTUTTER chất bamboo sơ vin linh hoạt FIT SHIRT',
        color_info: 'trắng be, vàng cát, đen, xanh mint, ghi nhạt',
        size_info: '0/1/2/3 tương ứng với S/M/L/XL ',
        material: 'vải bamboo (thoáng mát và không nhăn)',
        form: 'vải bamboo (thoáng mát và không nhăn)',
        origin: 'Việt Nam',
        gender: 'nam',
    },
    {
        title: 'Sunflower Polo Tee',
        price: '194.000',
        priceold:'123.000',
        image01: 'https://github.com/quangloc2708/Ecommerce-Web-Shop/blob/main/src/assets/Images/products/prd3.1.jpeg?raw=true',
        image02: 'https://github.com/quangloc2708/Ecommerce-Web-Shop/blob/main/src/assets/Images/products/prd3.2.jpeg?raw=true',
        categorySlug: 'Áo thun',
        colors: ['black'],
        slug: 'sunflower-polo-tee',
        size: ['s', 'm', 'xl'],
        decription: 'Áo sơ mi nam form refined fit SSSTUTTER chất bamboo sơ vin linh hoạt FIT SHIRT',
        color_info: 'trắng be, vàng cát, đen, xanh mint, ghi nhạt',
        size_info: '0/1/2/3 tương ứng với S/M/L/XL ',
        material: 'vải bamboo (thoáng mát và không nhăn)',
        form: 'vải bamboo (thoáng mát và không nhăn)',
        origin: 'Việt Nam',
        gender: 'nam',
    },
    {
        title: 'Form Jeans-Ⅱ',
        price: '194.000',
        priceold:'123.000',
        image01: 'https://github.com/quangloc2708/Ecommerce-Web-Shop/blob/main/src/assets/Images/products/prd4.1.jpeg?raw=true',
        image02: 'https://github.com/quangloc2708/Ecommerce-Web-Shop/blob/main/src/assets/Images/products/prd4.2.jpeg?raw=true',
        categorySlug: 'Quần jean',
        colors: ['white', 'red', 'orange', 'blue'],
        slug: 'form-jeans-II',
        size: ['l', 'xl'],
        decription: 'Áo sơ mi nam form refined fit SSSTUTTER chất bamboo sơ vin linh hoạt FIT SHIRT',
        color_info: 'trắng be, vàng cát, đen, xanh mint, ghi nhạt',
        size_info: '0/1/2/3 tương ứng với S/M/L/XL ',
        material: 'vải bamboo (thoáng mát và không nhăn)',
        form: 'vải bamboo (thoáng mát và không nhăn)',
        origin: 'Việt Nam',
        gender: 'nam',
    },
    {
        title: 'Check Conrad Shirt',
        price: '194.000',
        priceold:'123.000',
        image01: 'https://github.com/quangloc2708/Ecommerce-Web-Shop/blob/main/src/assets/Images/products/prd5.1.jpeg?raw=true',
        image02: 'https://github.com/quangloc2708/Ecommerce-Web-Shop/blob/main/src/assets/Images/products/prd5.2.jpeg?raw=true',
        categorySlug: 'Áo sơ mi',
        colors: ['white', 'red', 'black'],
        slug: 'conrad-shirt',
        size: ['s', 'm', 'xl'],
        decription: 'Áo sơ mi nam form refined fit SSSTUTTER chất bamboo sơ vin linh hoạt FIT SHIRT',
        color_info: 'trắng be, vàng cát, đen, xanh mint, ghi nhạt',
        size_info: '0/1/2/3 tương ứng với S/M/L/XL ',
        material: 'vải bamboo (thoáng mát và không nhăn)',
        form: 'vải bamboo (thoáng mát và không nhăn)',
        origin: 'Việt Nams',
        gender: 'nam',
    },
    {
        title: 'Great Tee',
        price: '194.000',
        priceold:'123.000',
        image01: 'https://github.com/quangloc2708/Ecommerce-Web-Shop/blob/main/src/assets/Images/products/prd6.1.jpeg?raw=true',
        image02: 'https://github.com/quangloc2708/Ecommerce-Web-Shop/blob/main/src/assets/Images/products/prd6.2.jpeg?raw=true',
        categorySlug: 'Áo thun',
        colors: ['white', 'blue'],
        slug: 'great-tee-2',
        size: ['m'],
        decription: 'Áo sơ mi nam form refined fit SSSTUTTER chất bamboo sơ vin linh hoạt FIT SHIRT',
        color_info: 'trắng be, vàng cát, đen, xanh mint, ghi nhạt',
        size_info: '0/1/2/3 tương ứng với S/M/L/XL ',
        material: 'vải bamboo (thoáng mát và không nhăn)',
        form: 'vải bamboo (thoáng mát và không nhăn)',
        origin: 'Việt Nams',
        gender: 'nam',
    },
    {
        title: 'Laplace Shirt',
        price: '194.000',
        priceold:'123.000',
        image01:'https://github.com/quangloc2708/Ecommerce-Web-Shop/blob/main/src/assets/Images/products/prd7.1.jpeg?raw=true',
        image02:'https://github.com/quangloc2708/Ecommerce-Web-Shop/blob/main/src/assets/Images/products/prd7.2.jpeg?raw=true',
        categorySlug: 'Áo sơ mi',
        colors: ['blue', 'black'],
        slug: 'laplace-shirt',
        size: ['l'],
        decription: 'Áo sơ mi nam form refined fit SSSTUTTER chất bamboo sơ vin linh hoạt FIT SHIRT',
        color_info: 'trắng be, vàng cát, đen, xanh mint, ghi nhạt',
        size_info: '0/1/2/3 tương ứng với S/M/L/XL ',
        material: 'vải bamboo (thoáng mát và không nhăn)',
        form: 'vải bamboo (thoáng mát và không nhăn)',
        origin: 'Việt Nam',
        gender: 'nam',
    },
    {
        title: 'Sss.Cable-Knit Jacket',
        price: '194.000',
        priceold:'123.000',
        image01: 'https://github.com/quangloc2708/Ecommerce-Web-Shop/blob/main/src/assets/Images/products/prd8.1.jpeg?raw=true',
        image02: 'https://github.com/quangloc2708/Ecommerce-Web-Shop/blob/main/src/assets/Images/products/prd8.2.jpeg?raw=true',
        categorySlug: 'Áo sơ mi',
        colors: ['blue', 'black'],
        slug: 'cable-knit-jacket',
        size: ['s', 'm', 'xl'],
        decription: 'Áo sơ mi nam form refined fit SSSTUTTER chất bamboo sơ vin linh hoạt FIT SHIRT',
        color_info: 'trắng be, vàng cát, đen, xanh mint, ghi nhạt',
        size_info: '0/1/2/3 tương ứng với S/M/L/XL ',
        material: 'vải bamboo (thoáng mát và không nhăn)',
        form: 'vải bamboo (thoáng mát và không nhăn)',
        origin: 'Việt Nams',
        gender: 'nam',
    },
    {
        title: 'Classic Shirt',
        price: '194.000',
        priceold:'123.000',
        image01: 'https://github.com/quangloc2708/Ecommerce-Web-Shop/blob/main/src/assets/Images/products/prd9.1.jpeg?raw=true',
        image02: 'https://github.com/quangloc2708/Ecommerce-Web-Shop/blob/main/src/assets/Images/products/prd9.2.jpeg?raw=true',
        categorySlug: 'Áo sơ mi',
        colors: ['blue'],
        slug: 'classic shirt',
        size: ['s', 'm', 'xl'],
        decription: 'Áo sơ mi nam form refined fit SSSTUTTER chất bamboo sơ vin linh hoạt FIT SHIRT',
        color_info: 'trắng be, vàng cát, đen, xanh mint, ghi nhạt',
        size_info: '0/1/2/3 tương ứng với S/M/L/XL ',
        material: 'vải bamboo (thoáng mát và không nhăn)',
        form: 'vải bamboo (thoáng mát và không nhăn)',
        origin: 'Việt Nams',
        gender: 'nam',
    },
 

    {
        title: 'Unum Tank',
        price: '299.000',
        priceold:'123.000',
        image01: 'https://github.com/quangloc2708/Ecommerce-Web-Shop/blob/main/src/assets/Images/products-for-her/prd100.1.jpeg?raw=true',
        image02: 'https://github.com/quangloc2708/Ecommerce-Web-Shop/blob/main/src/assets/Images/products-for-her/prd100.2.jpeg?raw=true',
        categorySlug: 'Áo thun',
        colors: ['white', 'red', 'orange'],
        slug: 'ao-thun-05',
        size: ['s', 'm', 'l', 'xl'],
        decription: 'Áo sơ mi nam form refined fit SSSTUTTER chất bamboo sơ vin linh hoạt FIT SHIRT',
        color_info: 'trắng be, vàng cát, đen, xanh mint, ghi nhạt',
        size_info: '0/1/2/3 tương ứng với S/M/L/XL ',
        material: 'vải bamboo (thoáng mát và không nhăn)',
        form: 'vải bamboo (thoáng mát và không nhăn)',
        origin: 'Việt Nam',
        gender: 'nu',
    },
    {
        title: 'Summer Set Shirt 22',
        price: '349.000',
        priceold:'123.000',
        image01: 'https://github.com/quangloc2708/Ecommerce-Web-Shop/blob/main/src/assets/Images/products-for-her/prd101.1.jpeg?raw=true',
        image02: 'https://github.com/quangloc2708/Ecommerce-Web-Shop/blob/main/src/assets/Images/products-for-her/prd101.2.jpeg?raw=true',
        categorySlug: 'Quần tây',
        colors: ['white', 'red', 'blue'],
        slug: 'quan-02',
        size: ['s', 'm'],
        decription: 'Áo sơ mi nam form refined fit SSSTUTTER chất bamboo sơ vin linh hoạt FIT SHIRT',
        color_info: 'trắng be, vàng cát, đen, xanh mint, ghi nhạt',
        size_info: '0/1/2/3 tương ứng với S/M/L/XL ',
        material: 'vải bamboo (thoáng mát và không nhăn)',
        form: 'vải bamboo (thoáng mát và không nhăn)',
        origin: 'Việt Nam',
        gender: 'nu',
    },
    {
        title: 'Birdie Stripped Shirt',
        price: '379.000',
        priceold:'123.000',
        image01: 'https://github.com/quangloc2708/Ecommerce-Web-Shop/blob/main/src/assets/Images/products-for-her/prd102.1.jpeg?raw=true',
        image02: 'https://github.com/quangloc2708/Ecommerce-Web-Shop/blob/main/src/assets/Images/products-for-her/prd102.2.jpeg?raw=true',
        categorySlug: 'Áo sơ mi',
        colors: ['white', 'red', 'orange', 'yellow'],
        slug: 'ao-so-mi-01',
        size: ['m'],
        
        decription: 'Áo sơ mi nam form refined fit SSSTUTTER chất bamboo sơ vin linh hoạt FIT SHIRT',
        color_info: 'trắng be, vàng cát, đen, xanh mint, ghi nhạt',
        size_info: '0/1/2/3 tương ứng với S/M/L/XL ',
        material: 'vải bamboo (thoáng mát và không nhăn)',
        form: 'vải bamboo (thoáng mát và không nhăn)',
        origin: 'Việt Nam',
        gender: 'nu',
    },
    {
        title: 'Unum Shirt',
        price: '394.000',
        priceold:'123.000',
        image01: 'https://github.com/quangloc2708/Ecommerce-Web-Shop/blob/main/src/assets/Images/products-for-her/prd103.1.jpeg?raw=true',
        image02: 'https://github.com/quangloc2708/Ecommerce-Web-Shop/blob/main/src/assets/Images/products-for-her/prd103.2.jpeg?raw=true',
        categorySlug: 'Áo sơ mi',
        colors: ['white', 'orange', 'blue'],
        slug: 'ao-so-mi-02',
        size: ['xl'],
        decription: 'Áo sơ mi nam form refined fit SSSTUTTER chất bamboo sơ vin linh hoạt FIT SHIRT',
        color_info: 'trắng be, vàng cát, đen, xanh mint, ghi nhạt',
        size_info: '0/1/2/3 tương ứng với S/M/L/XL ',
        material: 'vải bamboo (thoáng mát và không nhăn)',
        form: 'vải bamboo (thoáng mát và không nhăn)',
        origin: 'Việt Nam',
        gender: 'nu',
    },
    {
        title: 'Low Waist Skort',
        price: '294.000',
        priceold:'123.000',
        image01: 'https://github.com/quangloc2708/Ecommerce-Web-Shop/blob/main/src/assets/Images/products-for-her/prd104.1.jpeg?raw=true',
        image02: 'https://github.com/quangloc2708/Ecommerce-Web-Shop/blob/main/src/assets/Images/products-for-her/prd104.2.jpeg?raw=true',
        categorySlug: 'Váy',
        colors: ['white', 'pink'],
        slug: 'vay-03',
        size: ['m', 's'],
        decription: 'Áo sơ mi nam form refined fit SSSTUTTER chất bamboo sơ vin linh hoạt FIT SHIRT',
        color_info: 'trắng be, vàng cát, đen, xanh mint, ghi nhạt',
        size_info: '0/1/2/3 tương ứng với S/M/L/XL ',
        material: 'vải bamboo (thoáng mát và không nhăn)',
        form: 'vải bamboo (thoáng mát và không nhăn)',
        origin: 'Việt Nam',
        gender: 'nu',
    },
    {
        title: 'Split Midi Skirt',
        price: '499.000',
        priceold:'123.000',
        image01: 'https://github.com/quangloc2708/Ecommerce-Web-Shop/blob/main/src/assets/Images/products-for-her/prd105.1.jpeg?raw=true',
        image02: 'https://github.com/quangloc2708/Ecommerce-Web-Shop/blob/main/src/assets/Images/products-for-her/prd105.2.jpeg?raw=true',
        categorySlug: 'Váy',
        colors: ['black'],
        slug: 'vay-04',
        size: ['s', 'm', 'xl'],
        decription: 'Áo sơ mi nam form refined fit SSSTUTTER chất bamboo sơ vin linh hoạt FIT SHIRT',
        color_info: 'trắng be, vàng cát, đen, xanh mint, ghi nhạt',
        size_info: '0/1/2/3 tương ứng với S/M/L/XL ',
        material: 'vải bamboo (thoáng mát và không nhăn)',
        form: 'vải bamboo (thoáng mát và không nhăn)',
        origin: 'Việt Nam',
        gender: 'nu',
    },
    {
        title: 'Paris Tee',
        price: '194.000',
        priceold:'123.000',
        image01: 'https://github.com/quangloc2708/Ecommerce-Web-Shop/blob/main/src/assets/Images/products-for-her/prd106.1.jpeg?raw=true',
        image02: 'https://github.com/quangloc2708/Ecommerce-Web-Shop/blob/main/src/assets/Images/products-for-her/prd106.2.jpeg?raw=true',
        categorySlug: 'Áo thun',
        colors: ['white', 'red', 'orange', 'blue'],
        slug: 'ao-thun-01',
        size: ['l', 'xl'],
        decription: 'Áo sơ mi nam form refined fit SSSTUTTER chất bamboo sơ vin linh hoạt FIT SHIRT',
        color_info: 'trắng be, vàng cát, đen, xanh mint, ghi nhạt',
        size_info: '0/1/2/3 tương ứng với S/M/L/XL ',
        material: 'vải bamboo (thoáng mát và không nhăn)',
        form: 'vải bamboo (thoáng mát và không nhăn)',
        origin: 'Việt Nam',
        gender: 'nu',
    },
    {
        title: 'Dots Mini Skirt',
        price: '394.000',
        priceold:'123.000',
        image01: 'https://github.com/quangloc2708/Ecommerce-Web-Shop/blob/main/src/assets/Images/products-for-her/prd107.1.jpeg?raw=true',
        image02: 'https://github.com/quangloc2708/Ecommerce-Web-Shop/blob/main/src/assets/Images/products-for-her/prd107.2.jpeg?raw=true',
        categorySlug: 'Áo sơ mi',
        colors: ['white', 'red', 'black'],
        slug: 'ao-so-mi-03',
        size: ['s', 'm', 'xl'],
        decription: 'Áo sơ mi nam form refined fit SSSTUTTER chất bamboo sơ vin linh hoạt FIT SHIRT',
        color_info: 'trắng be, vàng cát, đen, xanh mint, ghi nhạt',
        size_info: '0/1/2/3 tương ứng với S/M/L/XL ',
        material: 'vải bamboo (thoáng mát và không nhăn)',
        form: 'vải bamboo (thoáng mát và không nhăn)',
        origin: 'Việt Nam',
        gender: 'nu',
    },
    {
        title: 'Pocket Mini Skirt',
        price: '494.00',
        priceold:'123.000',
        image01:'https://github.com/quangloc2708/Ecommerce-Web-Shop/blob/main/src/assets/Images/products-for-her/prd108.1.jpeg?raw=true',
        image02: 'https://github.com/quangloc2708/Ecommerce-Web-Shop/blob/main/src/assets/Images/products-for-her/prd108.2.jpeg?raw=true',
        categorySlug: 'Váy',
        colors: ['white', 'blue'],
        slug: 'vay-05',
        size: ['m'],
        decription: 'Áo sơ mi nam form refined fit SSSTUTTER chất bamboo sơ vin linh hoạt FIT SHIRT',
        color_info: 'trắng be, vàng cát, đen, xanh mint, ghi nhạt',
        size_info: '0/1/2/3 tương ứng với S/M/L/XL ',
        material: 'vải bamboo (thoáng mát và không nhăn)',
        form: 'vải bamboo (thoáng mát và không nhăn)',
        origin: 'Việt Nam',
        gender: 'nu',
    },
    {
        title: 'Birdie Pants',
        price: '399.000',
        priceold:'123.000',
        image01: 'https://github.com/quangloc2708/Ecommerce-Web-Shop/blob/main/src/assets/Images/products-for-her/prd109.1.jpeg?raw=true',
        image02: 'https://github.com/quangloc2708/Ecommerce-Web-Shop/blob/main/src/assets/Images/products-for-her/prd109.2.jpeg?raw=true',
        categorySlug: 'Quần tây',
        colors: ['blue', 'black'],
        slug: 'quan-01',
        size: ['l'],
        decription: 'Áo sơ mi nam form refined fit SSSTUTTER chất bamboo sơ vin linh hoạt FIT SHIRT',
        color_info: 'trắng be, vàng cát, đen, xanh mint, ghi nhạt',
        size_info: '0/1/2/3 tương ứng với S/M/L/XL ',
        material: 'vải bamboo (thoáng mát và không nhăn)',
        form: 'vải bamboo (thoáng mát và không nhăn)',
        origin: 'Việt Nam',
        gender: 'nu',
    },
    {
        title: 'Bird Shirt 2022',
        price: '294.000',
        priceold:'123.000',
        image01: 'https://github.com/quangloc2708/Ecommerce-Web-Shop/blob/main/src/assets/Images/products-for-her/prd111.1.jpeg?raw=true',
        image02: 'https://github.com/quangloc2708/Ecommerce-Web-Shop/blob/main/src/assets/Images/products-for-her/prd111.2.jpeg?raw=true',
        categorySlug: 'Áo sơ mi',
        colors: ['blue', 'black'],
        slug: 'ao-so-mi-04',
        size: ['s', 'm', 'xl'],
        decription: 'Áo sơ mi nam form refined fit SSSTUTTER chất bamboo sơ vin linh hoạt FIT SHIRT',
        color_info: 'trắng be, vàng cát, đen, xanh mint, ghi nhạt',
        size_info: '0/1/2/3 tương ứng với S/M/L/XL ',
        material: 'vải bamboo (thoáng mát và không nhăn)',
        form: 'vải bamboo (thoáng mát và không nhăn)',
        origin: 'Việt Nam',
        gender: 'nu',
    },
    {
        title: 'Mona Lis Blazer',
        price: '194.000',
        priceold:'123.000',
        image01: 'https://github.com/quangloc2708/Ecommerce-Web-Shop/blob/main/src/assets/Images/products-for-her/prd111.2.jpeg?raw=true',
        image02: 'https://github.com/quangloc2708/Ecommerce-Web-Shop/blob/main/src/assets/Images/products-for-her/prd112.2.jpeg?raw=true',
        categorySlug: 'Áo sơ mi',
        colors: ['blue'],
        slug: 'ao-so-mi-05',
        size: ['s', 'm', 'xl'],
        decription: 'Áo sơ mi nam form refined fit SSSTUTTER chất bamboo sơ vin linh hoạt FIT SHIRT',
        color_info: 'trắng be, vàng cát, đen, xanh mint, ghi nhạt',
        size_info: '0/1/2/3 tương ứng với S/M/L/XL ',
        material: 'vải bamboo (thoáng mát và không nhăn)',
        form: 'vải bamboo (thoáng mát và không nhăn)',
        origin: 'Việt Nams',
        gender: 'nu',
    },
    {
        title: 'Compo Bodysuit',
        price: '189.000',
        priceold:'123.000',
        image01: 'https://github.com/quangloc2708/Ecommerce-Web-Shop/blob/main/src/assets/Images/products-for-her/prd113.1.jpeg?raw=true',
        image02: 'https://github.com/quangloc2708/Ecommerce-Web-Shop/blob/main/src/assets/Images/products-for-her/prd113.2.jpeg?raw=true',
        categorySlug: 'Áo thun',
        colors: ['white', 'red'],
        slug: 'ao-thun-02',
        size: ['s', 'm', 'xl'],
        decription: 'Áo sơ mi nam form refined fit SSSTUTTER chất bamboo sơ vin linh hoạt FIT SHIRT',
        color_info: 'trắng be, vàng cát, đen, xanh mint, ghi nhạt',
        size_info: '0/1/2/3 tương ứng với S/M/L/XL ',
        material: 'vải bamboo (thoáng mát và không nhăn)',
        form: 'vải bamboo (thoáng mát và không nhăn)',
        origin: 'Việt Nams',
        gender: 'nu',
    },
    {
        title: 'Poet Shirt',
        price: '459.000',
        priceold:'123.000',
        image01: 'https://github.com/quangloc2708/Ecommerce-Web-Shop/blob/main/src/assets/Images/products-for-her/prd114.1.jpeg?raw=true',
        image02: 'https://github.com/quangloc2708/Ecommerce-Web-Shop/blob/main/src/assets/Images/products-for-her/prd114.2.jpeg?raw=true',
        categorySlug: 'Áo sơ mi',
        colors: ['white', 'blue'],
        slug: 'ao-so-mi-06',
        size: ['s', 'm'],
        decription: 'Áo sơ mi nam form refined fit SSSTUTTER chất bamboo sơ vin linh hoạt FIT SHIRT',
        color_info: 'trắng be, vàng cát, đen, xanh mint, ghi nhạt',
        size_info: '0/1/2/3 tương ứng với S/M/L/XL ',
        material: 'vải bamboo (thoáng mát và không nhăn)',
        form: 'vải bamboo (thoáng mát và không nhăn)',
        origin: 'Việt Nams',
        gender: 'nu',
    },
    {
        title: 'plaid shorts',
        price: '399.000',
        priceold:'123.000',
        image01: 'https://github.com/quangloc2708/Ecommerce-Web-Shop/blob/main/src/assets/Images/products-for-her/prd115.1.jpeg?raw=true',
        image02: 'https://github.com/quangloc2708/Ecommerce-Web-Shop/blob/main/src/assets/Images/products-for-her/prd115.2.jpeg?raw=true',
        categorySlug: 'Quần jean',
        colors: ['red', 'blue'],
        slug: 'quan-02',
        size: ['xl'],
        decription: 'Áo sơ mi nam form refined fit SSSTUTTER chất bamboo sơ vin linh hoạt FIT SHIRT',
        color_info: 'trắng be, vàng cát, đen, xanh mint, ghi nhạt',
        size_info: '0/1/2/3 tương ứng với S/M/L/XL ',
        material: 'vải bamboo (thoáng mát và không nhăn)',
        form: 'vải bamboo (thoáng mát và không nhăn)',
        origin: 'Việt Nams',
        gender: 'nu',
    },
   
];

export const Policy:Array<policy> = [
    {
        name: 'Miễn phí giao hàng',
        description: 'Miễn phí ship với đơn hàng > 239K',
        icon: <AiOutlineShopping />,
        title:'Thanh toán thẻ (ATM, Visa , MasterCards)'
    },
    {
        name: 'Thanh toán COD',
        description: 'Thanh toán khi nhận hàng (COD)',
        icon: <AiOutlineCreditCard />,
        title:'Thanh toán khi giao hàng (COD)'
    },
    {
        name: 'Khách hàng VIP',
        description: 'Ưu đãi dành cho khách hàng VIP',
        icon: <BsFillXDiamondFill />,
        title:'Thanh toán thẻ (ATM, Visa , MasterCard)'
    },
    {
        name: 'Hỗ trợ bảo hành',
        description: 'Đổi, sửa đồ tại tất cả store',
        icon:<BiDonateHeart />,
        title:'Thanh toán bằng ví ShopeePay'
    },
];

export const FilterProducts:Array<filter>=[
    {
        id:1,
        name:'Áo thun'
    },
    {
        id:2,
        name:'Áo sơ mi'
    },
    {
        id:3,
        name:'Quần jean'
    },
    {
        id:4,
        name:'Quần tây'
    },
    {
        id:5,
        name:'Váy'
    },
]

export const FilterSizes:Array<filter>=[
    {
        id:6,
        name:'S'
    },
    {
        id:7,
        name:'M'
    },
    {
        id:8,
        name:'L'
    },
    {
        id:9,
        name:'XL'
    },
    {
        id:10,
        name:'XXL'
    },
]

export const FilterColors:Array<filter>=[
    {
        id:11,
        name:'White'
    },
    {
        id:12,
        name:'Pink'
    },
    {
        id:13,
        name:'Black'
    },
    {
        id:14,
        name:'Yellow'
    },
    {
        id:15,
        name:'Red'
    },
    {
        id:16,
        name:'Blue'
    }
]






